version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 203918861989.dkr.ecr.eu-north-1.amazonaws.com
      - REPOSITORY_URI=203918861989.dkr.ecr.eu-north-1.amazonaws.com/venlinkrepo

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image tagged as latest...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"vencontainer","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
