name: Deploy to AWS Fargate with Notifications

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  ECS_CLUSTER: VenlinkCluster
  ECS_SERVICE: VenLinkService
  ECS_TASK_DEFINITION: arn:aws:ecs:eu-north-1:203918861989:task-definition/VenlinkTaskDefinition:1
  SNS_TOPIC_ARN: arn:aws:sns:eu-north-1:203918861989:Demo

jobs:
  deploy:
    name: Deploy and Notify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Deploy to ECS
        id: deploy
        run: |
          aws ecs update-service \
            --cluster "$ECS_CLUSTER" \
            --service "$ECS_SERVICE" \
            --task-definition "$ECS_TASK_DEFINITION" \
            --force-new-deployment
      
      - name: Send Success Notification
        if: success()
        run: |
          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "Deployment Successful ✅" \
            --message "ECS Service $ECS_SERVICE deployed successfully!
            Cluster: $ECS_CLUSTER
            Task Definition: $ECS_TASK_DEFINITION"
      
      - name: Send Failure Notification
        if: failure()
        run: |
          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "Deployment Failed ❌" \
            --message "Failed to deploy ECS Service $ECS_SERVICE
            Cluster: $ECS_CLUSTER
            Task Definition: $ECS_TASK_DEFINITION"
