name: Deploy to AWS Fargate

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  ECS_CLUSTER: VenlinkCluster  # Update with your actual ECS cluster name
  ECS_SERVICE: VenLinkService  # Update with your ECS service name
  ECS_TASK_ID: 4dc178fd16904272810d8234a87b67b7
  SUBNETS: "subnet-0c398bfa1f35ed01b"
  SECURITY_GROUP: "sg-01eaa66fa10fa8a78"

jobs:
  deploy:
    name: Restart ECS Task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Stop Old ECS Task
        run: |
          aws ecs stop-task --cluster $ECS_CLUSTER --task $ECS_TASK_ID
      
      - name: Run Task Again
        run: |
          aws ecs run-task --cluster $ECS_CLUSTER \
            --task-definition $ECS_TASK_DEFINITION \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SECURITY_GROUP],assignPublicIp=\"ENABLED\"}"
